# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13, unique=True)),
                ('message', models.CharField(max_length=10000)),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_contact', models.CharField(max_length=100)),
                ('sender_company', models.CharField(max_length=100)),
                ('action_taken', models.CharField(max_length=10000)),
                ('date_action', models.DateTimeField(null=True)),
                ('remarks', models.CharField(max_length=5000, null=True)),
                ('done', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='office_referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Office'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Platform'),
        ),
    ]
