# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='action_taken',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sender_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sender_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sender_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
