# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20161025_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
