# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20161025_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.IntegerField(),
        ),
    ]
