# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20161025_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.CharField(max_length=8),
        ),
    ]
