# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20161027_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
