# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_category_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
